### ISSUE TITLE
Investigate and refactor dependencies

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/py2json#1]
Currently, `py2json` has these dependencies:

```
install_requires =
    boltons
    glom
    numpy
    i2
    anytree
    scikit-learn
    scipy
```

I’d like us to investigate the need for some of these. Especially the heavy ones like `scipy` and `scikit-learn`, and remove those we can to keep `py2json` light and focused on its concern.

**Comment by andeaseme** [comment]
We'll have to look into a standard way to have optional requirements. Make py2json.Ctor readily configurable. Maybe an Otosense repo for standard reusable tools configs that will be used in the majority of our projects to keep the tools light and still make using the tool seamless.

**Comment by andeaseme** [comment]
Also refactor `validate_conversion` using i2mint's tested package `tested.codecs.validate_codec`

**Comment by andeaseme** [comment]
Dependency for `scikit-learn`, `scipy`, and `anytree` are from `py2json/inspire` and [are easily removed as show in this commit](https://github.com/i2mint/py2json/commit/e389b9c0307e9642ad8193b93badb9d72340900f).  The `inspire` folder will not be included in the published package but still available in the git repo since it's code meant to be read and not used directly from py2json.
